source :rubygems

gem 'cramp', :git => 'git://github.com/rankin/cramp.git'

# Async webserver for running a cramp application
gem 'thin'

# Rack based routing
gem 'http_router'

# Collection of async-proof rack middlewares - https://github.com/rkh/async-rack.git
gem 'async-rack'

# For async Active Record models.
<% if active_record? -%>
gem 'activesupport', '3.2.11'

<% if database.eql?('mysql') -%>
gem 'mysql2', '~> 0.2.11'
<% else -%>
gem 'pg'
gem 'em-postgresql-adapter', :git => 'git://github.com/leftbee/em-postgresql-adapter.git'
<% end -%>
gem 'activerecord', '3.2.11', :require => 'active_record'
<% else -%>
#gem 'activesupport', '3.2.11'
#gem 'mysql2', '~> 0.2.11'
#gem 'pg'
#gem 'em-postgresql-adapter', :git => 'git://github.com/leftbee/em-postgresql-adapter.git'
#gem 'activerecord', '3.2.11', :require => 'active_record'
<% end -%>

# Using Fibers + async callbacks to emulate synchronous programming
<% if database.eql?('postgresql') -%>
gem 'em-synchrony', :git     => 'git://github.com/igrigorik/em-synchrony.git',
                    :require => ['em-synchrony',
                                 'em-synchrony/activerecord']
<% else -%>
# gem 'em-synchrony'
<% end -%>


# Generic interface to multiple Ruby template engines - https://github.com/rtomayko/tilt
# gem 'tilt'

group :development do
  # Development gems
  # gem 'ruby-debug19'
end
